apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  labels:
    testing.upbound.io/example-name: sh01-eus2-02
  name: sh01-eus2-02
spec:
  managementPolicies: ["Observe", "Create", "Update", "Delete"]
  initProvider:
    microsoftDefender:
      - logAnalyticsWorkspaceId: "/subscriptions/e049fcf1-c84b-4de4-ba9a-a168a4cbab7a/resourcegroups/DefaultResourceGroup-USW3/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-e049fcf1-c84b-4de4-ba9a-a168a4cbab7a-USW3"
    monitorMetrics:
      - annotationsAllowed: "pods=[*]"
      - labelsAllowed: "pods=[*]"
    omsAgent:
      - logAnalyticsWorkspaceId: "/subscriptions/e049fcf1-c84b-4de4-ba9a-a168a4cbab7a/resourceGroups/prod-clu-grp01/providers/Microsoft.OperationalInsights/workspaces/perfclusterlogs"
      - msiAuthForMonitoringEnabled: true
  forProvider:
    defaultNodePool:
      - name: default
        vmSize: Standard_D4s_v4
        enableAutoScaling: true
        maxCount: 5
        minCount: 1
    dnsPrefix: sh01-eus2-02
    identity:
      - type: SystemAssigned
    oidcIssuerEnabled: true
    workloadIdentityEnabled: true
    keyVaultSecretsProvider:
      - secretRotationEnabled: true

    nodeOsChannelUpgrade: SecurityPatch
    location: East US 2
    azurePolicyEnabled: true
    resourceGroupName: prod-clu-grp01
    tags:
      Environment: Production
      Location: Seattle
      Owner: piere
