apiVersion: compute.example.com/v1alpha1
kind: backend-data-tier-small
metadata:
  name: pier62
spec: 
  location: EU
  appname: pier62
  repourl: https://github.com/danielsollondon/backend-datatier
  repopath: helm-chart/
  branchname: not62