apiVersion: v1
kind: Namespace
metadata:
  name: <K8s-NAMESPACE>
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: core-app-testing
    namespace: argocd
spec:
    project: default
    source:    
        repoURL: https://YOUR-URL
        targetRevision: HEAD
        path: staging         
    syncPolicy:
        automated: {}
    destination:
        namespace:  <K8s-NAMESPACE>
        server: https://kubernetes.default.svc
