apiVersion: v1
kind: Namespace
metadata:
  name: ${appName}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: stdappquota
  namespace: ${appName}
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 8Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: ${USER_ASSIGNED_CLIENT_ID}
  name: ${appName}
  namespace: ${appName}
---
cat <<EOF | kubectl apply -f -
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-app-env-vars
  namespace: ${appName}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "${USER_ASSIGNED_CLIENT_ID}" # Setting this to use workload identity
    keyvaultName: ${KEYVAULT_NAME}       # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: "${KEYVAULT_SECRET_NAME}"   
          objectType: secret
    tenantId: "${TENANT_ID}"                 # The tenant ID of the key vault                              
  secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: "${KEYVAULT_SECRET_NAME}"                             # data field to populate
      objectName: "${KEYVAULT_SECRET_NAME}"                           # name of the mounted content to sync; this could be the object name or the object alias
    secretName: "${KEYVAULT_SECRET_NAME}"                     # name of the Kubernetes secret object
    type: Opaque                              # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)
---
kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline-user-msi
  namespace: ${appName}
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: ${appName}
  containers:
    - name: busybox
      image: k8s.gcr.io/e2e-test-images/busybox:1.29-1
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
      env:
      - name: db-conn-string
        valueFrom:
          secretKeyRef:
            name: "${KEYVAULT_SECRET_NAME}" 
            key: "${KEYVAULT_SECRET_NAME}" 
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: spc-app-env-vars
     

